### ISSUE TITLE
Way around incomplete list of Scripts?

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/schema#1]
Following a conversation with Benjamin Kiessling (@mittagessen) today, and having noticed the issue with the RASAM dataset (@CVidalG), it seems necessary to have a way to handle the problem of the incompleteness of the list of scripts.

I open this issue so we can talk about potential solutions.

--

AC:
> I guess an option would be to allow custom script identifier when it doesn't exist in the listing

BK:
> Yes, you need that definitely. The problem with ISO 15924 is that it mixes different levels of descriptors. There are identifiers for Latin and Fraktur, or Syriac variants but only one for Hebrew.

**Comment by PonteIneptique** [comment]
Linked to #4 
I would not like to open the list, but we can create, upon demand, custom identifier, even if I am not completely fond of it :)

**Comment by mittagessen** [comment]
In my opinion it would be better to remove values from the list that describe styles of a main script, more or less mapping them to their Unicode aliases and then allow a free text field to set the typographic variant. For example one would merge `Aran` into `Arab` and add a lower level descriptor of Nastaliq, `Syre, Syrj, Syrn` to `Syrc` with their respective styles, `Latf` and `Latg` into `Latn`, ...

There are most likely corner cases where there is dispute about what constitutes a writing system or merely a style but this seems to be at least an approach that is easy to deal with. There seems to be a list of writing systems [here](https://www.worldswritingsystems.org) that is done by actual linguists which may be could be the source of a better script list than ISO 15924 .

**Comment by PonteIneptique** [comment]
So, from my understandings, in terms of schema, this would mean:

`scripts` become an array of objects, with a required script ISO identifier, and a variant free text field.

That might require some work in terms of UI, but I think most people have one script, and this won't overload the UI of most people then. Just the one of people dealing with multiscripts :)

You'd be satisfied with that @mittagessen ?
