### ISSUE TITLE
Add ORCID to Contributor objects

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/schema#10]
Completely optional but it would be nice.

**Comment by alix-tz** [comment]
I'm taking any opinion on the pattern: https://github.com/HTR-United/schema/pull/9/commits/d4cce2c8ed4fe769e89a8f20d1710fda16f0a681


```json
"pattern": "^\\d{4}-\\d{4}-\\d{4}-\\d{4}$"
```
