### ISSUE TITLE
Add a "status" key

### ISSUE THREAD

**Issue by alix-tz** [HTR-United/schema#11]
Mostly to enable filtering only the "clean" dataset and be able to distinguish those which would still be "in progress".

(This issue was raised by Peter Stokes and Daniel Stoekl)

**Comment by PonteIneptique** [comment]
Hmmmmm....
I am not sure I agree with this one. The main reason being that I expect people to forget about the catalog once they dropped their dataset on it.

**Comment by alix-tz** [comment]
That's a good point!

I think one should not use a dataset without checking what is inside first, since the datasets are not curated by HTR-United (and maybe this should be stated explicitly somewhere on the website). But Peter and Daniel also made a good point saying that the reliability of the catalog lays on the fact that the datasets are not gibberish.

Peter asked: what if someone creates a dataset that contains super wrong transcriptions? How would you "remove" it from the catalog?

Also, if you take the example of CREMMA-MSS-XXX: some of them are still work in progress and probably need to be made more homogenous. Shouldn't they be signaled as "in progress"?

**Comment by PonteIneptique** [comment]
Décision 17/06/2022: Nobody changes the schema, but we add a button to report datasets.
