### ISSUE TITLE
Add "German Kurrent" or "Kurrent" as a script

### ISSUE THREAD

**Issue by thodel** [HTR-United/schema#4]
Add "German Kurrent" or "Kurrent" as a script-type in your form.
Since kurrent is not to be combined with latin scripts, a differentiation makes sense.

**Comment by PonteIneptique** [comment]
Hi @thodel ,
I simply transfered the issue to our schema repository :)

**Comment by thodel** [comment]
Thanks, @PonteIneptique for your reply.
It's not an idiotic question at all and it led me down some rabbit holes.

As it appears, the situation is complicated. In the anglophone Wikipedia article (and obviously in the ISO), there is a close similarity between "kurrent" to the typesetting "fraktur" assumed. Since fraktur is modeled after a specific bastarda (written by the royal chancery in Austria), both, Kurrent and Fraktur are derived from the Latin bastarda. Historically, both are latin (cursive) scripts.

Since a variety of letter-forms differ greatly between fraktur and kurrent (e.g. "n", "e") and with HTR systems in mind, I still would like to make an argument to differentiate between the two as well as Latin scripts (cursive or not). 
In my experience, the combination of Latin scripts of the early modern area with Kurrent scripts for HTR models usually doubles the amount needed for training (so for the systems the two are basically independent script types).

This leaves you with the decision of what to do. There's an argument for relying on iso and adding another category :-)
I'm happy with both solutions and looking forward to see, how HTR-United evolves!

**Comment by PonteIneptique** [comment]
@alix-tz I'd like your POV on this.
To me, here are our two options:

1. Having Kurrent as Latf (so basically fraktur, as read over Wikipedia)
2. Having `cust-latK` for a new ISO value.

**Comment by alix-tz** [comment]
I think being able to see rapidly which values have been added to the ISO list is important so I would go for the second option : `cust-Latk`

Later on, this might open discussion to add these values in the original ISO listing.

**Comment by PonteIneptique** [comment]
Hey @thodel,
Given the discussion in https://github.com/HTR-United/schema/issues/1, would you be okay with the following option: the new schema might have a free text field to qualify specific ISO. You could then use `Latf` as the script, and `Kurrent` in the free text field. Would that work out okay for you ? (I'd love to not touch ISO if we can :D )

**Comment by thodel** [comment]
Seems a great idea to me.

And please, I don't want to complicate things. The page is already immensely helpful :)

**Comment by PonteIneptique** [comment]
Done by #9, the catalog will support it by next week.
